# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

loom.platform=forge

# Minecraft / Forge
minecraft_version = 1.20.1
forge_version=47.4.16

# Mod Properties
mod_version = 0.1.1
maven_group = org.thinkingstudio
archives_base_name = constancy

# Dependencies
# ConnectedTexturesMod (CurseForge file ID for 1.20.1 Forge 1.1.10)
ctm_file_id = 5983309
